services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: eco_postgres_POO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5439:5432"   # внешний порт сменили на 5439, внутри контейнера всегда 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eco_postgres_POO
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "12345"
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx384m"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: